line-length = 120
unsafe-fixes = true

[lint]
extend-select = ["ALL"]

select = []
ignore = ["D100", "D104", "CPY001", "TC003", "TC001"]
fixable = []
unfixable = ["ALL"]

[per-file-ignores]
"exceptions.py" = ["D107"]